import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import React from "react";
import SessionProvider  from "./components/SessionProvider";

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLaout({children}) {
  return (
  
    <html lang="en" >
      <body>
        <Header />
        <hr />
        <SessionProvider>
          {children}
        </SessionProvider>
        <Footer />
      </body>
      </html>
  );
}
